### ISSUE TITLE
Allow Multisite users to access every blog

### ISSUE THREAD

**Issue by tianmarin** [kevinvess/wp-force-login#28]
In [wp-force-login](https://github.com/kevinvess/wp-force-login/blob/master/wp-force-login.php#L64) this plugin only `allow Multisite users access to their assigned sites`.

In my case, i need every registered user to view all sites.
I can comment those lines (and it works fine), but it would be a great if there were an option to toggle this behavior.

By the way, great plugin!

**Comment by kevinvess** [comment]
Great question and thanks for the praise!

Couldn't you just assign each user to all of your sites? I assume the answer is no because they've registered themselves for one site and you need it to be done automatically for the others?

Maybe try adding the [Join My Multisite](https://wordpress.org/plugins/join-my-multisite/) plugin to configure new user registration settings for each of your sites?

**Comment by kevinvess** [comment]
Did adding the [Join My Multisite](https://wordpress.org/plugins/join-my-multisite/) plugin resolve your issue?
