### ISSUE TITLE
Conflict with Wordfence

### ISSUE THREAD

**Issue by bacchusfugue** [kevinvess/wp-force-login#3]
When active, the plugin keeps Wordfence from scanning. Wordfence worked immediately after disabling force login.

**Comment by kevinvess** [comment]
The plugin blocks access to all page URLs without being a logged-in user by default (even for local actions); I believe you need to allow your localhost access to the wp-cron.php page to allow Wordfence to scan the site.

Try adding the following code to your theme's functions.php file:

```php
/**
 * Filter Force Login to allow exceptions for specific URLs.
 *
 * @return array An array of URLs. Must be absolute.
 **/
function my_forcelogin_whitelist() {
  return array(
    site_url( '/wp-cron.php' )
  );
}
add_filter('v_forcelogin_whitelist', 'my_forcelogin_whitelist', 10, 1);
```

Let me know if that worked for you.

**Comment by bacchusfugue** [comment]
Hi,
That didn't help, unfortunately.
I have been using the exceptions code for the landing page and contact
page, so that part works, just not with Wordfence.

**Comment by kevinvess** [comment]
I'm sorry about that, try adding this to your exceptions code:

```php
/**
 * Filter Force Login to allow exceptions for specific URLs.
 *
 * @return array An array of URLs. Must be absolute.
 **/
function my_forcelogin_whitelist() {
  return array(
    site_url( '/wp-cron.php' ),
    site_url( '/wp-admin/admin-ajax.php' )
  );
}
add_filter('v_forcelogin_whitelist', 'my_forcelogin_whitelist', 10, 1);
```

According to [this Wordfence support post](https://support.wordfence.com/support/solutions/articles/1000010338-my-scans-are-not-starting-what-should-i-do-), I think my plugin is not allowing your site to run any AJAX functionality while activated. Hopefully, by allowing the _admin-ajax.php_ file to run, your scans will work again.

You may need to allow the _wp-cron.php_ page to run as well, since that file is what allows plugins to run scheduled tasks.

Let me know if that works, thanks!

**Comment by bacchusfugue** [comment]
Unfortunately, that didn't work either. Not sure if this helps, but a
command to kill (stop) a scan does seem to process. It may just be a
function that doesnt require any special access, though.

**Comment by kevinvess** [comment]
Dang it! Ok, I will have to do some testing of my own I suppose.

For now though, you could try configuring your exceptions code like so:

```php
/**
 * Filter Force Login to allow exceptions for specific URLs.
 *
 * @return array An array of URLs. Must be absolute.
 **/
function my_forcelogin_whitelist() {
  // list of single page URLs
  $my_whitelist = array(
    site_url( '/wp-cron.php' ),
    site_url( '/wp-admin/admin-ajax.php' )
  );
  // allow any page URL if localhost
  if($_SERVER['REMOTE_ADDR'] == 127.0.0.1) {
    $my_whitelist[] = site_url($_SERVER['REQUEST_URI']);
  }
  return $my_whitelist;
}
add_filter('v_forcelogin_whitelist', 'my_forcelogin_whitelist', 10, 1);
```

**Comment by bacchusfugue** [comment]
Sorry it has taken me so long to try this - other projects demanding
atttention...
This code broke the functions.php with a "0" error

**Comment by kevinvess** [comment]
Sorry, add parentheses around the IP address:

```php
  if($_SERVER['REMOTE_ADDR'] == '127.0.0.1') {
```

**Comment by Arlen22** [comment]
Note that the $whitelist variable also needs to contain the query string, which is probably why it wasn't working with cron.php; because, if I'm not mistaken, most automatic calls to cron.php do have a query string.

Also, you probably want to add the current $whitelist to your code example, right? If more than one plugin is listening to the filter and they all return a $whitelist, the ones before them will be lost unless they send them along, right?

The code is modified from above, but I didn't test it.
```
/**
 * Filter Force Login to allow exceptions for specific URLs.
 * 
 * @param array The current whitelist if there are other plugins also listening to this filter.
 * @return array An array of URLs. Must be absolute.
 **/
function my_forcelogin_whitelist( $whitelist ) {
  // list of single page URLs
  $whitelist[] = site_url( '/wp-cron.php' . $_SERVER['REQUEST_URI'] ); //Didn't test this
  $whitelist[] = site_url( '/wp-admin/admin-ajax.php' );
  
  // allow any page URL if localhost
  if($_SERVER['REMOTE_ADDR'] == 127.0.0.1) {
    $whitelist[] = site_url($_SERVER['REQUEST_URI']);
  }
  return $whitelist;
}
add_filter('v_forcelogin_whitelist', 'my_forcelogin_whitelist', 10, 1);
```

**Comment by kevinvess** [comment]
@Arlen22 Interesting suggestions, but I'm not sure your use of `$_SERVER['REQUEST_URI']` with the wp-cron.php URL would work. I think you'd have to use something like this instead:

```php
// list of single page URLs
$whitelist[] = site_url( '/wp-cron.php?' . $_SERVER['QUERY_STRING'] ); //Didn't test this
```

**Comment by Arlen22** [comment]
Oh, wait, you're right. For some reason I though that the plugin whitelisted based on the query string as well, but you're right, it doesn't. So nevermind that. :)

**Comment by kevinvess** [comment]
I think passing the $whitelist array on was a good idea – though I also thought it's not likely another plugin is accommodating my plugin's filter, but hey – you never know. :)

**Comment by pryley** [comment]
You should probably allow wp-cron tasks through the whitelist by default, or at least provide an option.

**Comment by kevinvess** [comment]
I pushed an update that should solve the conflict with Wordfence or other plugins that rely on either wp-cron jobs or ajax requests: https://github.com/kevinvess/wp-force-login/commit/620d0d7efd2b4a7b4c720e328f4651ee8108c232

Please let me know if this fixes your issues or causes new ones; thanks!

**Comment by Arlen22** [comment]
I didn't test it, but what are you sure this wouldn't open up a site to someone reading it via ajax calls? Just asking, because I didn't test it or anything.

**Comment by kevinvess** [comment]
@Arlen22 It may open up a site to reading content via ajax calls, but I don't think there is any way around it. Many other plugins like Wordfence need access to ajax in order to function properly.

I think your concern is more of a general WordPress security issue than something I need to address within my plugin. Checkout this post about the issues with securing ajax calls in WordPress:
https://core.trac.wordpress.org/ticket/30742

For now, this isn't really a "security" plugin but just a quick and easy way to block the general public from viewing content on the website. I'm not sure many users are really concerned about a developer writing ajax calls to access their site content; but if they are – they should consider alternative or additional means to securing their website.
