### ISSUE TITLE
Not working for custom post type

### ISSUE THREAD

**Issue by WriteCraft** [kevinvess/wp-force-login#30]
The employee extranet has I'm using your plugin on has a custom post type and a page with a hyphen in the name 'this-type' rather than 'thistype' -- and that's the only page which I can see when I'm logged out.  All other urls take me to the login page just fine.  Any ideas on how I can make sure it is included?

**Comment by kevinvess** [comment]
Honestly– I'm not sure why that page wouldn't force you to login; unless your site has setup a bypass or whitelist filter for that page or post-type?

Or maybe there is a conflict with another plugin or your theme?

> a page with a hyphen in the name 'this-type' rather than 'thistype'

There are no other pages with a hyphen in the slug? Try creating a new page and make sure it has a hyphen in the URL, something like "test-page," and see if Force Login still works on that page. If you're forced to login– it's not caused by the hyphen, but something unique to that other page.

> has a custom post type

Force Login does not check for custom post types – unless you [added a filter to bypass](https://gist.github.com/kevinvess/641aad7cbe5bb42a751ef8ba7fee74ce) URLs based on that post type, it redirects you to login.

You'll need to run some tests to figure out why only that one page is not forced to login.

**Comment by WriteCraft** [comment]
Hi Kevin, thanks for the prompt answers!  It looks like this one was a page cache issue -- the page was redirecting to login properly this morning, so all is well.  Thanks!
