### ISSUE TITLE
Can't whitelist api routes for jwt authentication

### ISSUE THREAD

**Issue by valeryan** [kevinvess/wp-force-login#35]
Recent updates to force login has extended the reach of the plugin to the wp api. However, I already have a plugin that secures my wp api and I use JWT authentication to access the api. Your new `v_forcelogin_rest_access` does not include the same whitelist mechanism as force login as such any alternative api authentication is completely disable.  My simple plugin that I use to secure my api and use jwt authentication can be found here as an example. https://github.com/valeryan/wp-secure-api/blob/master/wp-secure-api.php. You could achieve something similar by applying the same whitelist logic to your api function.

**Comment by kevinvess** [comment]
I don't agree that a URL whitelist is appropriate or necessary for this. If you need to remove the API filter, try adding the following code to your functions.php file:

```php
remove_filter( 'rest_authentication_errors', 'v_forcelogin_rest_access' );
```

Thanks for using Force Login!

**Comment by valeryan** [comment]
Wordpress API Documentation list several plugins that can be used for authentication through the api https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/#authentication-plugins. However your plugin completely disables all of these plugins capability to authenticate. This is the equivalent of having force login also block access to the login page on wordpress. 

Removing the filter does not secure the rest of the API. Whitelisting an authentication url is way more appropriate than removing the security that the filter provides all together.

**Comment by kevinvess** [comment]
The new API filter in Force Login 5.1 allows requests with the authentication mechanism available natively within WordPress. I will consider options to allow these alternative modes of authentication, but I don't believe using a URL whitelist is the correct answer.

I had thought, maybe using a boolean bypass would be simpler to allow you to turn off the filter based on any condition (not just URL path) deemed necessary. But– then I thought you should be able to do just that using the `remove_filter()` function wrapped with whatever condition you need to only remove it for certain circumstances. For example:

```php
if ( $condition ) {
  remove_filter( 'rest_authentication_errors', 'v_forcelogin_rest_access' );
}
```

I agree, removing the filter does not secure the API – but you said you were already securing it using other methods. So, in your case, you may just remove the filter. For others, they may want to only remove it when a particular condition is met.

**Comment by kevinvess** [comment]
I looked into this a little further and I think the `v_forcelogin_rest_access` filter could be improved to allow alternative modes of authentication.

I'm using the `rest_authentication_errors` filter to enforce that a logged-in user is trying to access the API. Reference the [check_authentication()](https://github.com/WordPress/WordPress/blob/e8229a25d5f4c620ef5f021abe70224cc6c550de/wp-includes/rest-api/class-wp-rest-server.php#L102-L136) core function.

I'm thinking of updating my API filter to something like this:
```php
/**
 * Restrict REST API for authorized users only
 *
 * @param WP_Error|null|bool WP_Error if authentication error, null if authentication
 *                              method wasn't used, true if authentication succeeded.
 */
function v_forcelogin_rest_access( $result ) {
  if ( !is_user_logged_in() && null === $result ) {
    return new WP_Error( 'rest_unauthorized', __( "Only authenticated users can access the REST API.", 'wp-force-login' ), array( 'status' => rest_authorization_required_code() ) );
  }
  return $result;
}
add_filter( 'rest_authentication_errors', 'v_forcelogin_rest_access', 99, 1 );
```

Currently, I'm only checking if `! is_user_logged_in()` but I should also check if `null === $result` to ensure another authentication method wasn't used.

Unfortunately, I don't believe this will solve you issue because the [JWT Authentication plugin](https://github.com/Tmeister/wp-api-jwt-auth) does not pass its authentication result to the `rest_authentication_errors` filter.

If you check out the [OAuth 1.0a Server plugin](https://wordpress.org/plugins/rest-api-oauth1/), they [pass their authentication status to the filter](https://github.com/WP-API/OAuth1/blob/339fa7b38ce06d1ee98ca4dcb99ce45b64118322/oauth-server.php#L78), which my plugin can check against.

**Comment by aduth** [comment]
@kevinvess , I agree, this seems like something that could be improved by handling the filter at a later priority and deferring to the result of any other handling plugin. This seems consistent with core handling as well:

https://github.com/WordPress/wordpress-develop/blob/b8c4faf/src/wp-includes/rest-api.php#L750-L752

It would require that the plugin return some non-empty value to indicate an "okay" state, as you pointed out. This means the JWT plugin would need to be updated to `return true;` instead of the default `$result`. This can also be seen in the core implementation example:

https://github.com/WordPress/wordpress-develop/blob/b8c4faf/src/wp-includes/rest-api.php#L790

Two minor remarks on your code sample:

- It is possible `is_user_logged_in` incurs a database query via `WP_User::get_data_by` if the current user hasn't already been retrieved for the request, so I'd suggest reordering to the more trivial `empty( $result )` check first to take advantage of [short-circuit evaluation](https://en.wikipedia.org/wiki/Short-circuit_evaluation)
- The fourth argument to `add_filter` in your code is redundant since `1` is the default

**Comment by kevinvess** [comment]
@aduth Thanks for your input! Those are good points you made, I'll rework the code to include them and try to push a new release soon.

Thanks guys!
