### ISSUE TITLE
One Subsite Force Login

### ISSUE THREAD

**Issue by lindseyolson** [kevinvess/wp-force-login#38]
Hello, I noticed the plugin states that it works with multisites. Does the plugin just cover all subsites? Is there a feature that allows you to hook up to only 1 subsite of a multisite? I tried installing and I don't think this feature exists. Just wanted to double check and see if there were any future plans for building out this feature. Thank you!

**Comment by kevinvess** [comment]
It should work on a multisite install – and you should be able to activate it on a per-site basis or network wide. Check out this support thread for more info:

https://wordpress.org/support/topic/force-login-on-1-site-in-multi-site/

**Comment by lindseyolson** [comment]
Thank you! It works now. I did install it per the one site, but something goofy must have been happening. Thanks!

**Comment by kevinvess** [comment]
Excellent – I'm glad you got it working!

Don’t forget to [rate and review](https://wordpress.org/support/plugin/wp-force-login/reviews/#new-post) my plugin to let others know how you like it. Thanks!

**Comment by kevinvess** [comment]
Hi Lindsey,

Force Login shouldn't interfere with any logged-in user's actions, because it does nothing if the logged-in user is either a [Super Admin](https://developer.wordpress.org/reference/functions/is_super_admin/) or [is a member of the site](https://developer.wordpress.org/reference/functions/is_user_member_of_blog/) they're trying to access.

> Has any of your users experienced this?

This is the first I'm hearing of an issue with using the Customizer while Force Login is activated.

> [...] it either logs them out or says this:

What is the message it shows? I don't see it in your comment.

**Things to try:**

* Are you positive the logged-in user trying to customize the site is a Super Admin or a member of the given site?
* Does this issue still exist when you disable Force Login?
* Does this issue still exist when only Force Login is active?
