### ISSUE TITLE
Adds $_SERVER['SERVER_PORT'] to redirect_to

### ISSUE THREAD

**Issue by 1337cookie** [kevinvess/wp-force-login#48]
When no port is specified in the URL it adds $_SERVER['SERVER_PORT'] which in many cases is not the port that is open to users if using port forwarding or nginx redirection etc.

**Comment by kevinvess** [comment]
Force Login gets the visited URL for the `v_forcelogin_whitelist` filter and the $redirect_to variable. It includes the `$_SERVER['SERVER_PORT']` for WordPress installations which may not use the standard one (80) and could cause an infinite loop.

This was first reported and suggested here:
https://wordpress.org/support/topic/infinite-loop-when-server-port-is-not-standard/

Feel free to submit a PR with your suggested fix for this. Otherwise, you may use the `v_forcelogin_redirect` filter to remove the server port from your $redirect_to value.
