### ISSUE TITLE
Possible bug only in iPhone, redirects even when already logged in

### ISSUE THREAD

**Issue by guyinpv** [kevinvess/wp-force-login#50]
I have a somewhat complex site with a WooCommerce store. I am forcing login since it's a private store, but have made exceptions for pages like /register, /login, /password-reset, etc.

On all devices, desktop, and mobile, I've got everything working fine. On iPads and iPhones, whether using Safari or Chrome browsers, it often thinks every other page needs to login first, and constantly sends them to the login page with a redirect in the URL for going to the page they wanted.

So for example, I'm on the home page and click an "add to cart" button. The product goes into the cart and shows a flyout thing. Now I click on the "Cart" button to take me to the /cart page. Instead of going to the cart page, it directs me to the login page with a URL like:  https://example.com/wp-login.php?redirect_to=https%3A%2F%2Fexample.com%2Fcart%2F

I will do this when I click on a main menu item, the logo (home page link), cart, my account, etc. Even though I'm already logged in.

It's hard to troubleshoot from an iPhone since I don't have developer tools and such, so I'm limited on what I can test, except to say, when I disable the force login plugin, it doesn't do that any more.

**Comment by kevinvess** [comment]
Hi, thanks for using Force Login!

This doesn't sound like a bug with the plugin code, since it works "on all devices, desktop, and mobile."

Force Login determines if the user is logged-in based on the builtin WordPress function [is_user_logged_in()](https://developer.wordpress.org/reference/functions/is_user_logged_in/).

If the `is_user_logged_in()` function returns `false`, then the redirect happens.

Have you tried testing with your custom exceptions code removed? Have you tested using a default Twenty-* theme?

One thought, does your site force visitors to an HTTPS connection for all pages? WooCommerce tends to force an HTTPS connection when viewing the cart or checkout pages. Maybe when you went from the product page to the cart, it switched from HTTP page to an HTTPS page and thus required logging-in for HTTPS?

**Comment by guyinpv** [comment]
Thanks for the quick reply.

I'm limited and can't change the plugins or theme due to being a live store. They don't have staging I can use.

The site is set for HTTPS. They are on GoDaddy and it forces HTTPS from .htaccess.

One customer even reports that it "used to work". So maybe this is a brand new development?

Here is my v_forcelogin_whitelist:
```
$whitelist[] = home_url('/register/');
$whitelist[] = home_url('/login/');
$whitelist[] = home_url('/password-reset/');
```

Here is my v_forcelogin_bypass
```
$url_path = preg_replace('/\?.*/', '', $_SERVER['REQUEST_URI']);
$referrer = $_SERVER['HTTP_REFERER'];
if ('/password-reset/' === $url_path) {
  $bypass = true;
}
if ('/register/' === $url_path) {
  $bypass = true;
}
if ('/login/' === $url_path) {
  $bypass = true;
}

// Might be needed for SSO to work, this site acts as an SSO server
if (isset($_GET['oauth']) || isset($_POST['oauth'])) {
  $bypass = true;
}
if (preg_match("/wp-login/", $referrer) > 0) {
  $bypass = true;
}
if (preg_match("/wp-login\.php/", $_SERVER['REQUEST_URI']) > 0 && preg_match("/\/\/MYSITE\.com/", $referrer) > 0) {
  $bypass = true;
}
return $bypass;
```

This is all just for common pages. The site uses Elementor so the pass reset, register, etc are allowed to happen. Since this is also an SSO master, I'm allowing wp-login for the two-way handshake stuff to make sure Force Login does't interfere with SSO.

Most users complain just going to random pages in the site, such as the cart, or a product page. None of those pages are used as exceptions tho.

I might have thought this could be a Safari issue, but having installed Chrome on my iPhone and still have the problem, it seems to be Apple products only. Chrome on my Google Pixel works fine. So far this has been verified on multiple iPhones and tablets.

**Comment by kevinvess** [comment]
Ah– if you're using SSO, I suspect that is the cause of your issue.

Force Login may be redirecting you to the login screen (because it doesn't recognize the user as logged-in), but I suspect the cause of your issue lies with the SSO functionality.

As I've said, Force Login determines if the user is logged-in based on the builtin WordPress function [is_user_logged_in()](https://developer.wordpress.org/reference/functions/is_user_logged_in/).

This thread on the WP.org support forum might be useful to you:
https://wordpress.org/support/topic/using-this-plugin-with-oauth-sso/

Also, you shouldn't need to specify exceptions using both the `v_forcelogin_whitelist` and `v_forcelogin_bypass` filters. I recommend you stick with just the bypass filter.

Thanks and good luck!

**Comment by guyinpv** [comment]
I wish you'd look into this more. I still haven't been able to solve it.

Keep in mind that the site this is happening to is not the SSO slave site. This is actually the master site, so it's not even using SSO to log in, it's just logging in like a normal user. And again, it only wants to happen on Apple devices for no reason I can see. iPhones, iPads, etc.

Here is a typical experience:

1) I visit the site URL (on Apple, using Chrome, fresh incognito tab).
2) Force Login sends me to wp-login.php with a redirect to the home page in the URL. is_user_logged_in() is false, as expected.
3) I log in. It redirects me to the home page. As expected.
4) I click on WooCommerce button to take me to /cart page.
5) I'm redirected immediately to wp-login.php with a redirect to the /cart page in the URL. My is_user_logged_in() test says false, this shouldn't be the case! I can refresh the page (F5) over and over and it will keep tested false.
6) I open the address bar and remove the redirect parameters and just go directly to wp-login.php. The page reloads and now the logged in test is TRUE, it shows I'm logged in.
7) I can also go directly to the /cart page by typing in the address bar, the page opens and I'm logged in.
8) I may click some other link such as to go back to the home page, and once again it redirects to the login page, showing I'm not logged in. And again I can directly go to any page and it loads and shows me as logged in.

The only time WP seems to think I'm not logged in, is when I click links between pages, but only on Apple. And even then it can be inconsistent. Sometimes (rarely), the page will actually load without redirecting.

I believe is_user_logged_in() is returning inconsistent results but I don't know why or how it would be doing this. Maybe it's not Force Login's fault, but perhaps the testing of user status could be more robust to account for possible snags? Are there any other ways to test for login?

This is a very confusing situation to tshoot. The login test function can't be returning false only when clicking links between pages, but true when visiting a page directly. Something must be going on.

Just thought I'd let you know, in case this gets solved, you could make note of it in the docs.

**Comment by guyinpv** [comment]
I think I finally fixed it, and I do believe it was something GoDaddy was doing. 
They had to completely reset my whole account and configuration and database and file permissions and everything down the line. Took them a couple hours but when it was done, it finally started working on Apple devices again.

I don't know if it's worth it adding this to any notes anywhere, but GoDaddy really messed with this functionality.
