### ISSUE TITLE
Logout Redirect

### ISSUE THREAD

**Issue by nessamaia** [kevinvess/wp-force-login#55]
Hello.

The redirect to the inicial page after the login is not working after the user logout. 

I notice that the parameter `redirect_to` is lost after the logout. It makes the user been redirected to the WordPress painel.

**Comment by kevinvess** [comment]
Hi– thanks for using Force Login!

Force Login only sets the `redirect_to` parameter when the plugin redirects the visitor to the login screen. Logout does not trigger the Force Login redirect to the login screen because it's the same screen.

However, you can use the [login_redirect](https://developer.wordpress.org/reference/hooks/login_redirect/) filter to check for an empty `redirect_to` parameter and set a specific URL to always default redirects to on successful login.

For example:

```
/**
 * Set the URL to redirect to on login.
 *
 * @param string           $redirect_to           The redirect destination URL.
 * @param string           $requested_redirect_to The requested redirect destination URL passed as a parameter.
 * @param WP_User|WP_Error $user                  WP_User object if login was successful, WP_Error object otherwise.
 * @return string URL to redirect to on login. Must be absolute.
 **/
function my_login_redirect( $redirect_to, $requested_redirect_to, $user ) {
    if ( empty( $requested_redirect_to ) ) {
        return home_url();
    } else {
        return $redirect_to;
    }
}
add_filter( 'login_redirect', 'my_login_redirect', 10, 3 );
```

Related support topic:
https://wordpress.org/support/topic/redirect-filter-does-not-work-when-logging-in-after-logout/#post-6246889
