### ISSUE TITLE
Register is not working

### ISSUE THREAD

**Issue by PurpelAngel** [kevinvess/wp-force-login#59]
Hello! I'm using Force Login 5.5 with 

WP5.5.3
Buddypress  6.4.0
Colorlib Login Customizer .2.97

The Login works fine but REGISTER is not working at all.

Cheers
Egon

**Comment by kevinvess** [comment]
This is because you're using the BuddyPress plugin, which generates a custom registration URL.

You will need to add a bypass to Force Login to allow public access to those custom URLs. [Check out the FAQ's](https://github.com/kevinvess/wp-force-login/wiki/Frequently-Asked-Questions) to details on how to bypass specific pages.

Also, check out this support thread for an example of how to bypass BuddyPress registration pages:
https://wordpress.org/support/topic/force-login-with-site-using-buddypress-plugin/#post-12312223
