### ISSUE TITLE
Blocked Wordpress Mobile App Access

### ISSUE THREAD

**Issue by Running-VincentW** [kevinvess/wp-force-login#6]

**Comment by kevinvess** [comment]
This issue was already addressed here:
https://github.com/kevinvess/wp-force-login/issues/4

The plugin blocks access to all page URLs by default; you need to allow public access to the XML-RPC page to allow the Android or iOS app to access your site.

Add the following code to your theme's functions.php file:

```php
/**
 * Filter Force Login to allow exceptions for specific URLs.
 *
 * @return array An array of URLs. Must be absolute.
 **/
function my_forcelogin_whitelist() {
  return array(
    site_url( '/xmlrpc.php' )
  );
}
add_filter('v_forcelogin_whitelist', 'my_forcelogin_whitelist', 10, 1);
```
