### ISSUE TITLE
Fails to force image and PDF requests to login page

### ISSUE THREAD

**Issue by toomanyairmiles** [kevinvess/wp-force-login#74]
It appears that if you request an image or PDF from my site (the contents of which are confidential) users can access the information without the request being forced to the login page. You do have to know the URL first of course, but this wasn't my expectation. 

Bug or feature!?

**Comment by kevinvess** [comment]
Unfortunately, this isn’t something the plugin controls since no php or WordPress script runs prior to loading static files (.pdf, .doc, .jpg…etc). Your server just loads the file.

If you want to restrict access to the uploaded media files, you’ll have to configure your server to pass or “proxy” all requests to the uploads folder through a php script that can check if the user is logged-in.

Check out the following URL for an example of how to do this:
http://wordpress.stackexchange.com/a/37743/48165
